FROM python:3.12.5-slim-bookworm

RUN apt-get update && \
    apt-get install -y python3 python3-pip

WORKDIR /opt/app

COPY ./frontend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

COPY ./frontend .

CMD ["streamlit", "run", "main.py"]
