services:
  script-cpu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: script-cpu
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    restart: "no"
    volumes:
      - ./data:${INPUT_FILES_DIR}
      - ${LOCAL_HUGGINGFACE_MODELS}:${HUGGINGFACE_MODELS}
    environment:
      - HF_HOME=${HUGGINGFACE_MODELS}
    env_file:
      - .env
