services:
  script-cpu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: script-cpu
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    restart: "no"
    volumes:
      - ./models:/opt/app/models
      - ./data:${INPUT_FILES_DIR}
    env_file:
      - .env
